use chrono::Local;

use crate::model::session::ConnectionConfig;
use crate::model::variable::{VarDef, VarType};

/// Generate a C# class string from `config` and `var_defs`.
///
/// The output is compatible with the snap7dotnet `ReadClass<T>` pattern.
pub fn generate_csharp(config: &ConnectionConfig, var_defs: &[VarDef]) -> String {
    let datetime = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
    let db = config.db_number;

    let mut out = String::new();
    out.push_str("// Auto-generated by Siemens PLC Monitor\n");
    out.push_str(&format!("// DB: {} | Generated: {}\n", db, datetime));
    out.push_str("// Compatible with snap7dotnet ReadClass<T>\n");
    out.push('\n');
    out.push_str(&format!("public class DB{} {{\n", db));
    for var in var_defs {
        out.push_str(&generate_property(var));
    }
    out.push_str("}\n");
    out
}

fn generate_property(var: &VarDef) -> String {
    let name = &var.name;
    let byte_off = var.byte_offset;

    match &var.var_type {
        VarType::Bool => format!(
            "    public bool {} {{ get; set; }} // Byte {}, Bit {}\n",
            name, byte_off, var.bit_offset
        ),
        VarType::Byte => format!(
            "    public byte {} {{ get; set; }} // Byte {}\n",
            name, byte_off
        ),
        VarType::Word => format!(
            "    public ushort {} {{ get; set; }} // Byte {}\n",
            name, byte_off
        ),
        VarType::Int => format!(
            "    public short {} {{ get; set; }} // Byte {}\n",
            name, byte_off
        ),
        VarType::DWord => format!(
            "    public uint {} {{ get; set; }} // Byte {}\n",
            name, byte_off
        ),
        VarType::DInt => format!(
            "    public int {} {{ get; set; }} // Byte {}\n",
            name, byte_off
        ),
        VarType::Real => format!(
            "    public float {} {{ get; set; }} // Byte {}\n",
            name, byte_off
        ),
        VarType::String { length } => {
            let mut s = String::new();
            for i in 1..=*length {
                s.push_str(&format!(
                    "    public byte {}_{} {{ get; set; }} // Byte {}\n",
                    name,
                    i,
                    byte_off + i - 1
                ));
            }
            let byte_refs: Vec<String> = (1..=*length).map(|i| format!("{}_{}", name, i)).collect();
            s.push_str(&format!(
                "    public string {} =>\n        System.Text.Encoding.ASCII.GetString(new byte[] {{ {} }}).TrimEnd('\\0');\n",
                name,
                byte_refs.join(", ")
            ));
            s
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::session::ConnectionConfig;
    use crate::model::variable::{VarDef, VarType};

    fn cfg(db: u32) -> ConnectionConfig {
        ConnectionConfig { db_number: db, ..ConnectionConfig::default() }
    }

    fn def(name: &str, vt: VarType, byte: u32, bit: u8) -> VarDef {
        VarDef { name: name.to_string(), var_type: vt, byte_offset: byte, bit_offset: bit }
    }

    #[test]
    fn bool_produces_public_bool() {
        let out = generate_csharp(&cfg(1), &[def("flag", VarType::Bool, 0, 0)]);
        assert!(out.contains("public bool flag"));
    }

    #[test]
    fn bool_includes_bit_comment() {
        let out = generate_csharp(&cfg(1), &[def("flag", VarType::Bool, 2, 5)]);
        assert!(out.contains("Byte 2, Bit 5"));
    }

    #[test]
    fn byte_produces_public_byte() {
        let out = generate_csharp(&cfg(1), &[def("raw", VarType::Byte, 3, 0)]);
        assert!(out.contains("public byte raw"));
    }

    #[test]
    fn word_produces_ushort() {
        let out = generate_csharp(&cfg(1), &[def("status", VarType::Word, 4, 0)]);
        assert!(out.contains("public ushort status"));
    }

    #[test]
    fn int_produces_short() {
        let out = generate_csharp(&cfg(1), &[def("temp", VarType::Int, 6, 0)]);
        assert!(out.contains("public short temp"));
    }

    #[test]
    fn dword_produces_uint() {
        let out = generate_csharp(&cfg(1), &[def("counter", VarType::DWord, 8, 0)]);
        assert!(out.contains("public uint counter"));
    }

    #[test]
    fn dint_produces_int() {
        let out = generate_csharp(&cfg(1), &[def("pos", VarType::DInt, 12, 0)]);
        assert!(out.contains("public int pos"));
    }

    #[test]
    fn real_produces_float() {
        let out = generate_csharp(&cfg(1), &[def("pressure", VarType::Real, 16, 0)]);
        assert!(out.contains("public float pressure"));
    }

    #[test]
    fn string_produces_n_byte_properties() {
        let out = generate_csharp(&cfg(1), &[def("tag", VarType::String { length: 4 }, 10, 0)]);
        assert!(out.contains("public byte tag_1"));
        assert!(out.contains("public byte tag_2"));
        assert!(out.contains("public byte tag_3"));
        assert!(out.contains("public byte tag_4"));
        assert!(!out.contains("public byte tag_5"));
    }

    #[test]
    fn string_byte_offsets_are_sequential() {
        let out = generate_csharp(&cfg(1), &[def("s", VarType::String { length: 3 }, 5, 0)]);
        assert!(out.contains("// Byte 5"));
        assert!(out.contains("// Byte 6"));
        assert!(out.contains("// Byte 7"));
    }

    #[test]
    fn string_helper_property_uses_arrow() {
        let out = generate_csharp(&cfg(1), &[def("tag", VarType::String { length: 2 }, 0, 0)]);
        assert!(out.contains("public string tag =>"));
    }

    #[test]
    fn string_helper_contains_all_byte_names() {
        let out = generate_csharp(&cfg(1), &[def("msg", VarType::String { length: 3 }, 0, 0)]);
        assert!(out.contains("msg_1") && out.contains("msg_2") && out.contains("msg_3"));
    }

    #[test]
    fn header_contains_db_number() {
        let out = generate_csharp(&cfg(42), &[]);
        assert!(out.contains("DB: 42"));
    }

    #[test]
    fn empty_vars_produces_valid_class_skeleton() {
        let out = generate_csharp(&cfg(100), &[]);
        assert!(out.contains("public class DB100 {"));
        assert!(out.contains("}\n"));
    }

    #[test]
    fn class_name_uses_db_number() {
        let out = generate_csharp(&cfg(7), &[]);
        assert!(out.contains("public class DB7"));
    }
}
